services:
  postgres:
    image: postgres:15
    container_name: personel_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: personeltayindb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: personel_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  personeltayin:
    image: personeltayin:latest
    container_name: personeltayin
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - postgres
      
volumes:
  db-data: